#!/usr/bin/env python3
"""
Ruff Configuration Template (Python equivalent of eslint.config.js)

Demonstrates how to programmatically generate a ruff.toml for a Python project,
with linting rules that mirror the ESLint patterns:
  - unused variables  -> warn  (F841 in ruff)
  - undefined names   -> error (F821 in ruff)

Usage:
    python3 ruff-config-template.py                  # print config to stdout
    python3 ruff-config-template.py --write          # write ruff.toml to project root
    python3 ruff-config-template.py --write --path . # write to a specific directory
"""

import argparse
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration definition (mirrors eslint.config.js structure)
# ---------------------------------------------------------------------------

RUFF_CONFIG: dict = {
    # Target Python version (analogous to ecmaVersion: 2022)
    "target-version": "py312",
    # Files / directories to include (analogous to files: ["**/*.js"])
    "include": ["**/*.py"],
    # Line length limit
    "line-length": 88,

    "lint": {
        # Rules to enable:
        #   F841 = local variable assigned but never used  (no-unused-vars -> warn)
        #   F821 = undefined name                          (no-undef       -> error)
        #   E    = pycodestyle error codes
        #   W    = pycodestyle warning codes
        #   I    = isort import ordering
        "select": ["E", "W", "F", "I"],

        # Treat F841 (unused variable) as a warning, not an error.
        # Ruff does not have per-rule severity yet; the closest equivalent
        # is to list it in `extend-ignore` (silence) or keep it in `select`
        # and rely on `--exit-zero` for warnings. We document the intent here.
        "ignore": [],

        # Per-file ignores (analogous to ESLint per-file overrides)
        "per-file-ignores": {
            # Test files may use fixtures that look like unused variables
            "tests/**/*.py": ["F841"],
            "test_*.py": ["F841"],
        },
    },

    "format": {
        # Use double quotes (Python community default)
        "quote-style": "double",
        # Indent with spaces
        "indent-style": "space",
    },
}


# ---------------------------------------------------------------------------
# TOML serialisation (stdlib only, no external deps)
# ---------------------------------------------------------------------------

def _to_toml_value(value: object, indent: int = 0) -> str:
    """Recursively serialise a Python value to a TOML value string."""
    pad = "    " * indent
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, list):
        items = ", ".join(_to_toml_value(v) for v in value)
        return f"[{items}]"
    if isinstance(value, dict):
        lines = []
        for k, v in value.items():
            if isinstance(v, dict):
                # Nested tables rendered inline for simplicity
                inner = ", ".join(f'"{ik}" = {_to_toml_value(iv)}' for ik, iv in v.items())
                lines.append(f"{pad}    {k} = {{{inner}}}")
            else:
                lines.append(f"{pad}    {k} = {_to_toml_value(v)}")
        return "{" + ", ".join(f'{k} = {_to_toml_value(v)}' for k, v in value.items()) + "}"
    return repr(value)


def dict_to_toml(cfg: dict, section: str = "") -> str:
    """Convert a nested dict to TOML text (simple, sufficient for ruff.toml)."""
    lines: list[str] = []

    scalars: dict = {}
    tables: dict = {}

    for key, val in cfg.items():
        if isinstance(val, dict):
            tables[key] = val
        else:
            scalars[key] = val

    # Scalar keys first
    for key, val in scalars.items():
        lines.append(f'{key} = {_to_toml_value(val)}')

    # Nested tables
    for key, val in tables.items():
        sub_section = f"{section}.{key}" if section else key
        lines.append(f"\n[{sub_section}]")
        for sub_key, sub_val in val.items():
            if isinstance(sub_val, dict):
                # per-file-ignores style: dict of str -> list
                lines.append(f"[{sub_section}.{sub_key}]")
                for file_pat, rule_list in sub_val.items():
                    lines.append(f'"{file_pat}" = {_to_toml_value(rule_list)}')
            else:
                lines.append(f"{sub_key} = {_to_toml_value(sub_val)}")

    return "\n".join(lines)


def generate_toml() -> str:
    header = (
        "# ruff.toml — generated by ruff-config-template.py\n"
        "# Equivalent to eslint.config.js for Python projects.\n"
        "#\n"
        "# Rule equivalences:\n"
        "#   no-unused-vars (warn)  ->  F841  (local variable assigned but never used)\n"
        "#   no-undef       (error) ->  F821  (undefined name)\n"
        "#\n"
        "# Run linter:   ruff check .\n"
        "# Run formatter: ruff format .\n\n"
    )
    return header + dict_to_toml(RUFF_CONFIG)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a ruff.toml configuration file for Python projects"
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write ruff.toml to the target directory instead of printing to stdout",
    )
    parser.add_argument(
        "--path",
        type=Path,
        default=Path("."),
        metavar="DIR",
        help="Directory where ruff.toml will be written (default: current directory)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    toml_text = generate_toml()

    if args.write:
        target = args.path / "ruff.toml"
        target.write_text(toml_text, encoding="utf-8")
        print(f"Written: {target.resolve()}")
    else:
        sys.stdout.write(toml_text + "\n")


if __name__ == "__main__":
    main()
